const mockElections = [
  {
    zkvoteBy: "Cosmos12sf123412y346781234781234asdasflj",
    assignedVoters: 800,
    votedNow: 300,
    electionId: 234123412341231,
    name: "Trump mı kazanır Harris mi?",
    description: "Contrary to popular belief, Lorem Ipsum is not.",
    date: "1 Jan 2024",
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/5/56/Donald_Trump_official_portrait.jpg",
    ],
    listOfVoters: [
      "B62qn71Re1CnnJxbmUmDVE7mgVY2Y82mdCwGLg5DKkJeyHfC7qGKiG2",
      "123123",
      "1433123",
      "123123",
    ],
    choices: ["Trump", "Harris", "Biden", "Obama"],
    DAChoicesName: ["Avail", "Celestia"],
    DAChoicesDescription: [
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
    ],
    DAChoicesFee: [1.2593, 1.4212],
    DAChoicesCurrency: ["$AVAIL", "$CELE"],
  },
  {
    zkvoteBy: "UserXYZ",
    assignedVoters: 500,
    electionId: 234123412341222,
    votedNow: 200,
    name: "Which is better: React or Angular?",
    description: "An age-old debate between two popular frameworks.",
    date: "15 Feb 2024",
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
    ],
    choices: ["Angular", "React"],
    DAChoicesName: ["Avail", "Celestia"],
    DAChoicesDescription: [
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
    ],
    DAChoicesFee: [1.2593, 1.4212],
    DAChoicesCurrency: ["$AVAIL", "$CELE"],
  },
  {
    zkvoteBy: "Alice",
    assignedVoters: 1000,
    electionId: 234123412341233,
    votedNow: 750,
    name: "Best programming language in 2023?",
    description: "Help us decide the best programming language.",
    date: "10 Mar 2024",
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/1/18/C_Programming_Language.svg",
    ],
    choices: ["Java", "C", "C++", "Camel"],
    DAChoicesName: ["Avail", "Celestia"],
    DAChoicesDescription: [
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
    ],
    DAChoicesFee: [1.2593, 1.4212],
    DAChoicesCurrency: ["$AVAIL", "$CELE"],
  },
  {
    zkvoteBy: "Bob",
    assignedVoters: 300,
    electionId: 234123412341244,
    votedNow: 150,
    name: "Remote work vs Office work?",
    description: "Which work environment do you prefer?",
    date: "20 Apr 2024",
    images: ["https://via.placeholder.com/150/0000FF/FFFFFF?text=Remote+Work"],
    choices: ["Remote", "Office", "Hybrid"],
    DAChoicesName: ["Avail", "Celestia"],
    DAChoicesDescription: [
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
    ],
    DAChoicesFee: [1.2593, 1.4212],
    DAChoicesCurrency: ["$AVAIL", "$CELE"],
  },
  {
    zkvoteBy: "Carol",
    assignedVoters: 400,
    electionId: 234123412341255,
    votedNow: 100,
    name: "Android vs iOS?",
    description: "Choose your favorite mobile operating system.",
    date: "5 May 2024",
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/d/d7/Android_robot.svg",
    ],
    choices: ["IOS", "Android"],
    DAChoicesName: ["Avail", "Celestia"],
    DAChoicesDescription: [
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
    ],
    DAChoicesFee: [1.2593, 1.4212],
    DAChoicesCurrency: ["$AVAIL", "$CELE"],
  },
  {
    zkvoteBy: "Dave",
    assignedVoters: 600,
    electionId: 234123416641234,
    votedNow: 350,
    name: "Coffee or Tea?",
    description: "Which beverage do you prefer?",
    date: "25 Jun 2024",
    images: [
      "https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG",
    ],
    choices: ["Soft", "asdasd", "Bidasdfen", "Obadfma"],
    DAChoicesName: ["Avail", "Celestia"],
    DAChoicesDescription: [
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
      "It is a long established fact that a reader will be distracted by the readable content of a page.",
    ],
    DAChoicesFee: [1.2593, 1.4212],
    DAChoicesCurrency: ["$AVAIL", "$CELE"],
  },
];

export default mockElections;
