services:
  celestia-light-node:
    build:
      context: .
      args:
        GO_VERSION: 1.23.0
        REPO: https://github.com/celestiaorg/celestia-node.git
        PROJECT_FOLDER: celestia-node
        CHAIN_ID: mocha
        DAEMON_NAME: celestia
        DAEMON_HOME: /root/.celestia-light-mocha-4
        DAEMON_VERSION: v0.16.2-mocha
        DEFAULT_KEY_NAME: my_celes_key
        DEFAULT_RPC_PORT: 10102
        NODE_TYPE: light
        RPC_ENDPOINT: rpc-mocha.pops.one
        CELESTIA_OTEL_URL: otel.celestia.tools:4318
        TRUSTED_BLOCK_HASH: TRUSTED_BLOCK_HASH_PLACEHOLDER
        TRUSTED_BLOCK_HEIGHT: TRUSTED_BLOCK_HEIGHT_PLACEHOLDER
    container_name: zkvote-node-celestia
    restart: always
    ports:
      - 10102:10102